<script>
  import { onMount } from "svelte";
  import { convertTime } from "./util/timezone.js";
  import Map from "./components/Map.svelte";
  export let ready;
  let cases = [];
  let lastChecked = "";
  let loading = true;
  onMount(async () => {
    const res = await fetch(
      "https://covid-19-coronavirus-statistics.p.rapidapi.com/v1/stats?country=USA",
      {
        method: "GET",
        headers: {
          "x-rapidapi-host": "covid-19-coronavirus-statistics.p.rapidapi.com",
          "x-rapidapi-key": "704cfcb0e1mshf21690e8e0c9810p18115bjsn95c3d3ce320a"
        }
      }
    );
    const json = await res.json();
    cases = json.data.covid19Stats;
    lastChecked = json.data.lastChecked;
    if (cases.length !== 0) {
      loading = false;
    }
    if (lastChecked !== "") {
      lastChecked =
        convertTime(lastChecked) === undefined
          ? lastChecked
          : convertTime(lastChecked);
    }
  });
</script>

<style>
  :global(body) {
    padding: 0;
  }

  main {
    text-align: center;
    padding: 1em;
    max-width: 240px;
    margin: 0 auto;
  }

  h1 {
    color: #ff3e00;
    text-transform: uppercase;
    font-size: 4em;
    font-weight: 100;
  }

  @media (min-width: 2px) {
    main {
      max-width: none;
    }
  }
</style>

<svelte:head>

  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAmcKSbu2c0vVsK6HMARddIqYXfp_udkS8&callback=initMap"
    async
    defer>

  </script>
</svelte:head>

<main>
  {#if ready && !loading}
    <h1>Covid-19 cases in the USA</h1>
    <h3>Most recent update: {lastChecked}</h3>
    <p>
      The data used for this map is generated by an API. The data for each state
      is updated on different days, so some states may not be up to date.
      <b>For the most part, this is recent data!</b>
    </p>
    <Map {cases} />
  {:else}
    <p>Loading...</p>
  {/if}

</main>
